함께하는 사람 출력 시 자기 자신도 출력
slamapp/client pull request #51
Opened 2022-01-24 08:10 UTC by Parkserim

## 💁 설명 
함께하는 사람 출력 시 자기 자신도 출력해 주기
## 🔗 연결된 이슈 

closes #16 

## 🚨 PR 포인트 

- 초기에는 자기 자신을 me라고 표기했는데 유저이름이 나오면 명확할 것 같아서 추가해보았습니다.
- 유저 이름 뒤에 (me)를 추가하는 것이 좋을까요? 아니면 없는게 좋을까요? (현재 PR은 없는 코드입니다.)

## 📸 스크린 샷 
<img width="312" alt="스크린샷 2022-01-24 15 41 52" src="https://user-images.githubusercontent.com/33405125/150743531-a6c4815f-2200-4d08-a0ff-c59674f1053e.png">
<img width="313" alt="스크린샷 2022-01-24 15 41 35" src="https://user-images.githubusercontent.com/33405125/150744716-626cb825-ed75-403c-bdb1-3c48ea3f5994.png">

2022-01-26 08:16 UTC, grighth12 commented on src/components/domain/FollowListItem/index.tsx
> +        ) : isFollowed ? (
`p2` 
isFollowed를 통해서 자기자신이라면 팔로우 버튼을 출력하지 않는 방식으로 보입니당. 
자기자신이라는 의미가 명확할 수 있도록 FollowListItem의 props에 isMe(props명이 적절할지 모르겠습니다😅)를 추가하고, isMe로 조건부 렌더링을 해주는게 더 명확할 것 같아요

2022-01-26 08:21 UTC, manudeli requested changes
기존 코드를 수정하는 이슈가 필요하겠네요!

제안 받아주시고 Re-request review 눌러주시면 approval 누르겠습니다

2022-01-26 08:21 UTC, manudeli commented on src/components/domain/ReservationItem/ReservationItemBottom/index.tsx
> +          )}
이렇게 하면 어떨까요? profileImageUrl은 로그인된 유저의 프로필이 null일 수도 있어요
그래서 null인 프로필이미지를 가지고 있는 유저는 여기에 FollowListItem이 보이지 않을 거에요
그럼 잘못 동작되는 거겠죠?

```suggestion
          {userId && (
            <FollowListItem userId={userId} src={profileImageUrl || "/assets/default_profile.svg"}>
              {nickname}
            </FollowListItem>
          )}
```

2022-01-26 08:21 UTC, manudeli commented on src/components/domain/ReservationItem/ReservationItemBottom/index.tsx
> +          )}
FollowListItem 의 src가 string만 받을 수 있게 되어 있네요~
profileImageUrl || 'defaultUrl을' 일단 넣는 것으로 해결합시다
이슈에 Profile은 domain Component으로 분리하는 작업 추가해놓겠습니다

2022-01-26 08:21 UTC, manudeli commented on src/components/domain/ReservationItem/ReservationItemBottom/index.tsx
> +          )}
제안 받아주세요 approve할게요

2022-01-26 08:25 UTC, limkhl commented
저는 개인적으로는 me 표시가 있으면 좋을 것 같은데 텍스트로 `(me)` 라고 표기하는 것보다는 원래 팔로우 버튼이 들어가는 영역에 별도의 badge UI 표시해주는 게 디자인적으로 더 좋아보이긴 해요. 하지만 디자인이 확정되지 않았으니 우선은 이대로 머지해도 될 것 같아요!

2022-01-26 08:25 UTC, limkhl approved these changes
저는 개인적으로는 me 표시가 있으면 좋을 것 같은데 텍스트로 `(me)` 라고 표기하는 것보다는 원래 팔로우 버튼이 들어가는 영역에 별도의 badge UI 표시해주는 게 디자인적으로 더 좋아보이긴 해요. 하지만 디자인이 확정되지 않았으니 우선은 이대로 머지해도 될 것 같아요!

2022-01-26 08:26 UTC, manudeli commented on src/components/domain/FollowListItem/index.tsx
> +        ) : isFollowed ? (
@grighth12 @limkhl 
저는 isMe가 없어도 된다면 저는 가능한 Props를 줄여서 외부 의존성을 줄이는 쪽이 좋은 거 같아요

domain 컴포넌트인 만큼 authContext의 currentUser의 userId를 적극적으로 활용해주시면 좋을 거 같아요
그러면 FollowListItem의 props.userId와 비교하셔서 조건부 렌더링을 해줄 수 있다고 생각해요

2022-01-26 08:30 UTC, grighth12 commented
(me) 표시 글자는 Text base 보다 더 작으면 좋겠어요!

2022-01-26 08:42 UTC, manudeli approved these changes

2022-01-26 08:42 UTC, manudeli commented on src/components/domain/ReservationItem/ReservationItemBottom/index.tsx
> +          )}
좋습니다 approval 드릴게요
후에 Avatar들 domain으로 wrapping한 컴포넌트들을 만듭시다

2022-01-26 08:56 UTC, merged

2022-06-06 05:58 UTC, manudeli commented
@all-contributors please add @Parkserim for code doc design ideas review