feat: 프로필 이미지 편집 기능 구현
slamapp/client pull request #55
Opened 2022-01-24 13:55 UTC by limkhl

## 💁 설명 

## 🔗 연결된 이슈 

closes #17 

## 🚨 PR 포인트 

- 한나랑 마누가 도와주신 덕분에 프로필 이미지 수정을 마치고 프로필 페이지로 이동했을 때 수정된 이미지가 반영되지 않는 문제를 해결했습니다!
- Upload 컴포넌트 안에 있는 input의 files 값을 상위 컴포넌트에서 가져오기 위해 useRef를 Upload 컴포넌트 바깥으로 빼게 됐는데 이게 적절한지 살짝 의문입니다. 🤔
- axios interceptor에서 authFileRequest fetcher의 header에 Authorization이 제대로 들어가지 않는 문제가 있어서 조금 수정했습니다.

## 📸 스크린 샷

2022-01-25 03:37 UTC, manudeli requested changes
수정하면 훨씬 좋아질 거 같습니다! 코드가 기대가 되네요👍

async와 await를 더 명확하게 아시면 더 좋을 거 같아요! 오늘 공부하신다 하시니 request changes로 리뷰할게요

2022-01-25 03:37 UTC, manudeli commented on src/components/domain/ProfileForm/index.tsx
> +                )
`p4` 이렇게 리팩토링 하면 어떨까요?

```suggestion
               <Avatar isEdit src={isEdit ? fileSrc : profileImage} shape="circle" __TYPE="Avatar" />
```

2022-01-25 03:37 UTC, manudeli commented on src/contexts/AuthProvider/index.tsx
> +      router.reload();
router.reload() 가 필요한가요?

2022-01-25 03:37 UTC, manudeli commented on src/contexts/AuthProvider/context.ts
> +  deleteMyProfileImage: () => Promise<void>;
`p1` Promise의 제네릭으로 void가 맞나요? 

```suggestion
  updateMyProfile: (editedUserProfile: EditableUserProfile) => Promise<any>;
  updateMyProfileImage: (editedProfileImageFile: File) => Promise<any>;
  deleteMyProfileImage: () => Promise<any>;
```

```m
"void" is a little like the opposite of any: the absence of having any type at all. You may commonly see this as the return type of functions that do not return a value
``` 

- 타입스크립트 공식 핸드북 void 설명
https://www.typescriptlang.org/docs/handbook/basic-types.html#void

2022-01-25 03:37 UTC, manudeli commented on src/pages/user/edit/index.tsx
> +  };
async await 키워드가 필요한가요?

2022-01-25 03:37 UTC, manudeli commented on src/pages/user/edit/index.tsx
> +    fetchProfile();
`p1` 이 경우에는 async await가 필요없어보여요

2022-01-25 03:37 UTC, manudeli commented on src/contexts/AuthProvider/index.tsx
>          payload: { deletedMyProfileImage },
`p1` deletedMyProfileImage가 null이죠?

profileImage는 null이어야 하지 않는지요
dispatch의 payload가 없어도 될거 같은데 authProvider의 reducer부터 수정이 필요해보이네요

2022-01-25 15:01 UTC, grighth12 commented on src/pages/user/edit/index.tsx
> +    fetchProfile();
아 이거 맞아요! 제가 그 때 필요하다고 설명드렸었는데 이것 저것 해보다보니 의미가 없는 async/await이더라구요...🥲
잘못 설명드려서 죄송합니다ㅠㅠ

2022-01-25 15:03 UTC, grighth12 commented on src/pages/user/edit/index.tsx
> +  };
요 부분도 마찬가지로 필요하지 않은 부분입니다! 궁금하신다면 내일 설명해볼게용🔥

2022-01-25 16:07 UTC, manudeli commented on src/contexts/AuthProvider/index.tsx
>          payload: { deletedMyProfileImage },
혹시 리뷰보시고 이해되지 않는다면 라이브로 이야기해요

2022-01-26 06:43 UTC, grighth12 reviewed
리뷰를 총총,,,

2022-01-26 06:43 UTC, grighth12 commented on src/components/base/Upload/index.tsx
> +    }
`p1` 
1. 요 부분이 필요해진 이유가 있을까요?
2. addEventListener를 하고 removeEventListener를 해주지 않으면 계속 쌓이지 않을까 생각했는데, reader가 gc의 대상이 되어 사라지면 이벤트 리스너도 사라지는 걸까용??

2022-01-26 06:43 UTC, grighth12 commented on src/components/base/Upload/index.tsx
> +  const [fileSrc, setFileSrc] = useState<string | ArrayBuffer | null>(null);
`p2` fileSrc도 필요하게 된 배경이 있을까요?

2022-01-26 06:43 UTC, grighth12 commented on src/utils/imageFileToFormData.ts
> +const imageFileToFormData = (profileImageFile: File | null, key: string) => {
`p2` 
1. 함수는 동사로 시작하면 어떨까요? ex) appendImageFileToFormData
2. imageFileToFormData가 한 곳에서만 쓰이는 것으로 보이는데 utils에 빼신건 미래의 어떤 상황을 염두해서일까용??👀

2022-01-26 11:03 UTC, limkhl commented on src/components/domain/ProfileForm/index.tsx
> +                )
[3433ad9](https://github.com/slamapp/client/pull/55/commits/3433ad9322e5fd3b8ba76513179c77ac2c78de0f)에서 수정 완료했습니다!

2022-01-26 11:05 UTC, limkhl commented on src/contexts/AuthProvider/index.tsx
> +      router.reload();
기본 프로필 이미지로 변경을 누른 다음에 reload를 해주지 않으면 이전 프로필 이미지를 보여주는 상태 그대로 있더라고요. 기본 프로필 이미지로 변경됐다는 걸 알려주려면 reload 해서 변경된 이미지를 보여줘야 할 것 같아요.

2022-01-26 11:05 UTC, limkhl commented on src/pages/user/edit/index.tsx
> +  };
3ef3523에서 수정했습니다!

2022-01-26 11:06 UTC, limkhl commented on src/pages/user/edit/index.tsx
> +    fetchProfile();
[3ef3523](https://github.com/slamapp/client/pull/55/commits/3ef3523a4824dedd13e3a46a98efdda213de1734)에서 수정했습니다!

2022-01-26 11:07 UTC, limkhl commented on src/contexts/AuthProvider/index.tsx
>          payload: { deletedMyProfileImage },
[f4e245](https://github.com/slamapp/client/pull/55/commits/f4e2451316855a941e2a191741f31c2c76505cdd)에서 수정했습니다!

2022-01-26 11:11 UTC, limkhl commented on src/components/base/Upload/index.tsx
> +    }
1. 아바타 컴포넌트로 업로드한 이미지 파일을 미리 보여주기 위해서 넣었어요. 아바타 컴포넌트의 src로 파일 주소를 넣어야 이미지를 보여줄 수 있는데, input이 value 값으로 가지고 있는 file의 주소를 추출하려면 저 코드를 넣어줘야 하더라고요.
2. 생각 못 해봤던 부분이네요! 알려주셔서 감사해요. [스택오버플로우](https://stackoverflow.com/questions/40804687/javascript-addeventlistener)에서 관련 글을 찾았는데 가비지콜렉터의 대상이 되는 건지 아닌지 정확하게 잘 모르겠어요 ㅠ 아무래도 클린업을 해주는 게 좋을 것 같아서 [da55c15](https://github.com/slamapp/client/pull/55/commits/da55c15ee5c6d32b70d6c6769be9d0359ed53285) 이 커밋에서 수정 완료했습니다.

2022-01-26 11:14 UTC, limkhl commented on src/components/base/Upload/index.tsx
> +  const [fileSrc, setFileSrc] = useState<string | ArrayBuffer | null>(null);
업로드한 파일 미리보기를 구현하기 위해서 input이 value 값으로 가지고 있는 file의 주소를 저장하기 위한 state를 만든 것입니다!

2022-01-26 11:19 UTC, limkhl commented on src/utils/imageFileToFormData.ts
> +const imageFileToFormData = (profileImageFile: File | null, key: string) => {
1. 좋은 의견이네요! 역시 클린코드 지킴이 👍 [b7d02bd](https://github.com/slamapp/client/pull/55/commits/b7d02bdbd14866e6caddd5ee9f011aede114ba14)에서 수정했습니다!
2. utils로 분리한 가장 큰 이유는 이미지 파일을 FormData를 변환하는 로직이 ProfileForm 컴포넌트에서 꼭 보여줘야 하는 부분은 아니라고 느꼈기 때문이에요! 그리고 새 농구장을 추가할 때 이미지 업로드 기능을 추가한다면 그때에도 재사용할 수 있을 것 같아요.

2022-01-26 11:21 UTC, limkhl commented
@manudeli @grighth12 영문을 모르겠지만 리뷰를 반영해서 origin 브랜치에 push 하려고 했는데 자꾸 충돌을 해결하라는 안내가 뜨고 충돌을 해결해도 여전히 origin 브랜치에 push 되지 않는 문제가 있어서 부득이하게 `git push --force`를 했어요 😥 그래서 남겨주신 리뷰와 커밋 간의 관계가 깨졌습니다. 불편을 드려 죄송해요. 😭

2022-01-26 11:25 UTC, manudeli commented
@limkhl rebase를 했기 때문인거 같아보이는데 push전에 rebase하셨나요?

2022-01-26 11:28 UTC, limkhl commented
> @limkhl rebase를 했기 때문인거 같아보이는데 push전에 rebase하셨나요?

네네 `git pull --rebase origin develop`를 했었어요!

2022-01-26 11:40 UTC, manudeli requested changes
한가지만 더 수정하면 좋을 거 같아요!
Context에서 reducer의 actionType과 Api의 실행 함수는 명확히 구분되어야 한다고 생각해요

뮤테이션하는 액션이 Api그 자체는 아니니까요

한번 더 request change 드렸어요!

2022-01-26 11:40 UTC, manudeli commented on src/service/fetcher/interceptor/getConfig.ts
> +        ...config.headers,
오우 이부분은 제가 axios interceptor수정하면서 빼먹고 갔네요 감사합니다!

2022-01-26 11:40 UTC, manudeli commented on src/contexts/AuthProvider/actionTypes.ts
>    DELETE_MY_PROFILE_IMAGE: "DELETE_MY_PROFILE_IMAGE",
`p1` 이부분은 SET_MY_PROFILE_IMAGE로 actionType을 주면 두가지를 통일할 수 있어보여요

deleteapi나 updateapi나 전역상태를 null이나 string으로 set 하니까요

context에서 뿌리는 authProvider의 함수들은 냅두되 합칠건 합치는 게 좋다고 생각해요

(아마 고민없이 Api명으로 다 통일하신거 같아서~ 역할이 다르다고 생각해요)

2022-01-26 11:46 UTC, manudeli commented
> > @limkhl rebase를 했기 때문인거 같아보이는데 push전에 rebase하셨나요?
> 
> 네네 `git pull --rebase origin develop`를 했었어요!

Commit의 부모가 rebase 되었기 때문에 remote와 local의 커밋들이 다른 부모를 바라보기때문이에요

그럴때는 force push가 맞습니다

2022-01-26 12:24 UTC, limkhl commented on src/contexts/AuthProvider/actionTypes.ts
>    DELETE_MY_PROFILE_IMAGE: "DELETE_MY_PROFILE_IMAGE",
아, 맞네요! 너무 좋은 의견인 것 같아요. 수정했습니다! [b5bd5d4f](https://github.com/slamapp/client/pull/55/commits/b5bd5d4fac74c03606ebad491fbd147ac5e4da97)마누 덕분에 AuthContext에 제대로 값이 들어가지 않는 버그를 발견해서 그것도 고쳤어요~ 감사합니다! 👍

2022-01-26 12:27 UTC, manudeli commented on src/contexts/AuthProvider/actionTypes.ts
>    DELETE_MY_PROFILE_IMAGE: "DELETE_MY_PROFILE_IMAGE",
좋아요 머지할게요!

2022-01-26 12:28 UTC, manudeli approved these changes

2022-01-26 12:28 UTC, merged

2022-02-07 16:46 UTC, manudeli commented on src/components/base/Upload/index.tsx
> +  const [fileSrc, setFileSrc] = useState<string | ArrayBuffer | null>(null);
이 부분의 문제를 해결 해놓았습니다.
아래 PR 참고해주세요
#92 

이해가 되지 않는다면 꼭 물어봐주세요

2022-06-06 05:57 UTC, manudeli commented
@all-contributors please add @limkhl for code doc design ideas review