reservation context api 적용, 에러 수정
slamapp/client pull request #56
Opened 2022-01-24 14:08 UTC by grighth12

## 💁 설명 

## 🔗 연결된 이슈 

closes 

## 🚨 PR 포인트 

- 사항1

## 📸 스크린 샷

2022-01-25 04:08 UTC, manudeli requested changes
기능에서 문제의 소지가 있어보이는 코드가 있어서 request changes로 할게요
정희님 코드보면서 저도 고민해볼 부분이 많아서 눈이 즐겁네요👍

2022-01-25 04:08 UTC, manudeli commented on src/components/domain/TimeTable/type.ts
> +  onClick: (index: number) => void;
`p2`
onClickStatusBlock을 onClick으로 일반적인 Attribute명으로 한건 저도 너무 좋아요

하지만 위 같은 타이핑이라면 한나(@grighth12)가 원하는 걸 아래 제안코드처럼 훨씬 간단히 구현할 수 있을 거같아요
혹시 아래 타입이 이해가 되지 않는다면 저를 라이브로 불러주세요 VScode를 직접 찍어가면서 봐야 효용이 보이기 때문에 보면서 설명드릴게요

```typescript
import type { DOMAttributes } from "react";

interface TestProps extends DOMAttributes<HTMLDivElement> {
  somethingWow: string;
}
```

2022-01-25 15:15 UTC, grighth12 commented on src/components/domain/CourtItem/Datetime.tsx
> +          {startDate.format("HH:mm")} - {endDate.format("HH:mm")}
분입니당!! 
PR에 설명된 내용 첨부드립니다🙂
- HH -> 24시간 시각표시, MM: 초에서 반올림하여 분 표시 라는 것을 알게 되었습니다. 정확한 시간 표기를 위해 HH:mm으로 포맷을 수정했습니다.
요런 차이가 있더라구요 신기합니다..

2022-01-25 15:16 UTC, grighth12 commented on src/contexts/ReservationProvider/context.ts
> +  handleSetTime: any;
참고로 저희는 p1, p2, p3만 있기로 결정했었습니다ㅠㅠㅋㅋㅋㅋ

2022-01-25 15:17 UTC, grighth12 commented on src/contexts/Providers.tsx
> +          </ReservationProvider>
이거 예전에 MapPovider를 할 때도 똑같이 존재했던 문제인데, 페이지 단에 프로바이더를 씌우면 context의 value들이 제대로 참조되지 않는 문제가 있습니다🥲
한 번 재시도 해보겠습니다..

2022-01-25 15:19 UTC, grighth12 commented on src/components/domain/TimeTable/index.tsx
>    useIsomorphicLayoutEffect(() => {
height는 DOM이 화면에 그려지기 전 빠르게 결정되기를 바래서 요부분은 이렇게 해보았습니다!
Isomorphic 자체는 마누도 아는 개념이고, 브라우저 환경이면 useLayoutEffect를 돌려주라는 hooks입니다.

useLayoutEffect에 대한 자세한 내용은 요기를 참고해보시기를 바랍니당 잘 설명되어있어요!
https://merrily-code.tistory.com/46

2022-01-25 15:21 UTC, grighth12 commented on src/components/domain/TimeTable/index.tsx
> +              isToday && !!currentTimeIndex && index < currentTimeIndex + 1
헉 이거 짚어주셔서 감사합니다
이거 분명 데일리로그에도 쓸만큼 기억에 남는 디버깅이었는데 또 같은 실수를 했네요
반영토록 하겠습니다

2022-01-25 15:25 UTC, grighth12 commented on src/components/domain/TimeTable/type.ts
> +  onClick: (index: number) => void;
HTMLDivElement의 기본 속성에 onClick과 같은 속성이 있기 때문에 extends 하는 걸까요??
일단 잘 모르겠으니 마누 특강 신청합니다✏️

2022-01-25 15:32 UTC, manudeli commented on src/components/domain/CourtItem/Datetime.tsx
> +          {startDate.format("HH:mm")} - {endDate.format("HH:mm")}
와우... 인사이트 감사합니다

2022-01-25 15:33 UTC, manudeli commented on src/contexts/ReservationProvider/context.ts
> +  handleSetTime: any;
아아 그렇군요!! `p3`로 수정할게요

2022-01-25 15:34 UTC, manudeli commented on src/contexts/Providers.tsx
> +          </ReservationProvider>
아아 지금처럼 useContext를 사용하면 크게 문제없다고 생각해요
일단 다른 거부터! 꼭 수정하실 필요없는 거 같아요

2022-01-25 15:35 UTC, manudeli commented on src/components/domain/TimeTable/type.ts
> +  onClick: (index: number) => void;
방금 답변주신 게 맞아요! 한번 해보시면 금방 아실겁니다 이거 아마 애용하게 될거에요

2022-01-25 16:05 UTC, manudeli commented on src/components/domain/TimeTable/index.tsx
>    useIsomorphicLayoutEffect(() => {
아!!! 와우 이거 너무 좋네요 그려지기전에 결정되기를 바란다... 크 좋습니다

2022-01-26 06:52 UTC, grighth12 commented on src/contexts/Providers.tsx
> +          </ReservationProvider>
요 문제 근데 언젠가는 해결해야 할 것 같다고 느껴서 언젠가는 디깅 해보도록 하겠습니다... 일단 요번에는 넘어갈게요ㅠㅠ~!!

2022-01-26 06:56 UTC, grighth12 commented on src/components/domain/TimeTable/type.ts
> +  onClick: (index: number) => void;
아 요거 뭔지 알았는데, 저는 이렇게 기본 props로 타입을 확장하는 방식을 선호하지 않습니다..!! 제게 필요한 props는 onClick 뿐인데, 아예 들어올 확률이 없는 props들이 타입에 존재하게 되는 게 좋지 않다고 생각해요

2022-01-26 07:05 UTC, grighth12 commented on src/components/domain/TimeTable/index.tsx
> +              isToday && !!currentTimeIndex && index < currentTimeIndex + 1
nulilsh 병합 연산자는 null일 때 오른쪽 피연산자를 반환하는 연산이더라구요..!! 그래서 이 경우에 활용하지는 못했습니다🥲 혹시 마누가 생각하신 방법이 있다면 말씀해주세요!

현재 currentTimeIndex의 null 검사를 명확히 하는 방안으로 해결했습니다.

isToday && currentTimeIndex !== null && index < currentTimeIndex + 1

2022-01-26 07:44 UTC, manudeli commented
![image](https://user-images.githubusercontent.com/61593290/151122725-a03fe888-19c2-4eca-8e70-f3373d6233ca.png)
한나 수정완료되면 Re-request review 버튼을 눌러주세요

2022-01-26 07:46 UTC, manudeli approved these changes

2022-01-26 07:47 UTC, merged

2022-01-26 07:47 UTC, grighth12 commented
@manudeli 확인했습니다~!

2022-01-31 13:09 UTC, limkhl commented on src/components/domain/CourtItem/Datetime.tsx
> +          )
`p3` 괄호의 차이에 따라 어떻게 달라지는 건지 궁금하네요?!

2022-01-31 13:11 UTC, limkhl commented on src/components/domain/ReservationModalContent/ExistedReservation.tsx
> +  }, []);
`p3` 이 부분 리팩토링하니까 의미가 훨씬 명확하고 넘 좋네요!

2022-06-06 05:54 UTC, manudeli commented
@all-contributors please add @grighth12 for bug code doc design ideas review test