:recycle: refactor: 접근성과 검색엔진최적화를 위한 기본 alt값 추가
slamapp/client pull request #63
Opened 2022-01-29 01:28 UTC by manudeli

## 💁 설명 
Lighthouse 테스트점수 향상시켰습니다. (즐겨찾기 페이지 기준)
- Accessibility: 74 -> 85점
- SEO: 92 -> 100점

나머지는 차차 채워가서 최고의 성능 최적화를 이뤄봅시다

## 🔗 연결된 이슈 

closes #62 

## 🚨 PR 포인트 
LinkAvatar와 Avatar에 alt을 기본값으로 주고 있습니다
후에 각 유저의 상황에 따라 alt를 manudeli's avatar등으로 수정하면 더 좋을 거 같습니다.

## 📸 PR 이전
![image](https://user-images.githubusercontent.com/61593290/151641624-14d3892b-8d31-42b7-adc9-f575a7867980.png)
![image](https://user-images.githubusercontent.com/61593290/151641633-973dff16-065c-4410-bc6c-a2d020a0319c.png)

## 📸 PR 이후
![image](https://user-images.githubusercontent.com/61593290/151641736-87109f67-4c2d-4980-98c9-69634c79c646.png)
![image](https://user-images.githubusercontent.com/61593290/151641721-ad4d9493-a056-4af7-ab0f-56e3ab452899.png)

2022-01-29 10:07 UTC, grighth12 requested changes
`p1` alt의 default 값을 빼고, Avatar나 LinkAvatar를 사용하는 곳에서 해당 유저의 닉네임을 넣어주면 더 명확한 alt 사용이 될 것 같아요! 깃헙이나 네이버를 살펴봤는데 둘다 유저명을 넣어놓더라구요😮
사소한 부분 신경써주셔서 고마워요 마누~!!

2022-01-29 11:14 UTC, manudeli commented
> `p1` alt의 default 값을 빼고, Avatar나 LinkAvatar를 사용하는 곳에서 해당 유저의 닉네임을 넣어주면 더 명확한 alt 사용이 될 것 같아요! 깃헙이나 네이버를 살펴봤는데 둘다 유저명을 넣어놓더라구요😮
> 사소한 부분 신경써주셔서 고마워요 마누~!!

default로 저렇게 넣어주고 각 필요한 곳에서 추가해주는 건 어떨까요?

avatar나 link_avatar라는 alt로써 아예 없는 것보다는 필요한 사람들 맹인 혹은 SEO로 충분히 의미있다고 생각해요

혹은 필수값으로 받게 하는 방법도 있을 거 같은데 그건 너무 엄격한 룰인 거 같아서요

필수값일 경우에는 넣을 만한 alt가 없을때 개발생산성이 떨어질 수 있으니까요

중간지점인 default를 넣어주고 계속 개선해가는 방식이면 좋겠어요 어떠신가요?

2022-01-29 11:20 UTC, grighth12 commented
넵 그래요~~!

2022-01-29 11:20 UTC, grighth12 approved these changes

2022-01-29 11:22 UTC, merged

2022-02-06 03:11 UTC, limkhl commented on src/components/base/Avatar/index.tsx
> +  alt = "avatar",
`p3` 리뷰가 늦어서 죄송해요! default로 alt 텍스트를 넣는 것 좋아요~ 그런데 우리가 우선적으로 한국어 유저를 위해 서비스한다면 alt 텍스트를 한글로 적어주는 게 더 좋을 것 같아요. 스크린 리더에서 영어를 좀 이상하게 읽어준다고 해서 확인해보니까 "애보터"라는 식으로 읽더라고요. 한국어로 바꾸는 게 좋을 것 같다고 생각하시면 현재 영어로 alt 텍스트 작성되어 있는 부분을 나중에 한번에 작업하는 게 좋을 듯 싶어서 우선 참고만 해주세요!

2022-02-06 03:28 UTC, manudeli commented on src/components/base/Avatar/index.tsx
> +  alt = "avatar",
오 그렇군요 한국어도 넣을 수 있는지 몰랐어요! 한국어로 나중에 바꿉시다~ 좋아요

Naver에도 한국어로 되어있네요 아래는 alt속성의 역할링크구요
https://ko.wikipedia.org/wiki/Alt_%EC%86%8D%EC%84%B1