Feat/reservation/confirm-modal
slamapp/client pull request #67
Opened 2022-01-29 11:56 UTC by grighth12

## 💁 설명 

## 🔗 연결된 이슈 

closes

## 🚨 PR 포인트 

- 사항1

## 📸 스크린 샷

2022-01-29 12:29 UTC, manudeli commented
`p1`
훨씬 예약과정이 명확해지고 좋네요
그런데 조금만 개선되면 더 좋을 거 같아요

1. 예약하시겠습니까?
'다음'보다는 '예약하기' 가 더 나을 거 같아요

2. 농구공을 가지고 참여하시나요?
현재처럼 아니오 / 네, 농구공을 가져갑니다를 양옆으로 쓰게 된다면 오른쪽 버튼에 더 강조가 되는데
선택이 위 아래로 된 같은 색의 버튼을 갖고 있는 모달이 좋아보여요

농구공을 보통 들고 가는 것은 아니니까요 안들고가는 사람이 더 많을텐데 현재 상태의 UI에서는 실수로 예를 클릭하는 경우가 더 많을 거에요

```
// 2번 모달 개선안 제안
농구공을 가지고 참여하시나요?

농구공을 가져가요
농구공을 안 가져가요
```
세로로 같은 검정색 (둘 다 예약이므로)

2022-01-29 12:57 UTC, manudeli requested changes
수고 많으셨어요!! 👍👍👍
변경점이 많은 파트를 맡으셨는데 섬세하고 좋네요! 계속 개선해봅시다

위에 말씀드린 버튼 텍스트, 색, 방향 방식은 어떠신가요? 이거 때문에 request changes 드렸어요

2022-01-29 12:57 UTC, manudeli commented on src/components/domain/ReservationModalContent/HasBallDecisionModal.tsx
> +};
`p3`
보통 enum의 경우 0 부터 시작할 거 같아요
근데 별로 안중요해서 그냥 두어도 상관은 없을 거 같아요ㅋㅋㅋ

2022-01-29 12:57 UTC, manudeli commented on src/contexts/ReservationProvider/reducer.ts
> +      console.log(selectedReservationId);
`p2`
console.log 있네요

저는 갠적으로 이렇게 배포되지 않은 개발 중에는 log를 어느정도 남기는 것도 개발생산성을 위해 좋아합니다

2022-01-29 12:57 UTC, manudeli commented on src/contexts/ReservationProvider/context.ts
>  }
`p3`
후에 타이핑 조집시다

제가 공유한 contextapi 타이핑 영상 보시면 좋을 거 같아요
혹시 이해가 안되시는 부분이 있다면 제가 라이브로 공유할게요

2022-01-29 12:57 UTC, manudeli commented on src/components/domain/TimeTable/index.tsx
>    } = useReservationContext();
`p2`
useReservationContext의 reservation은 예약이라는 명사로 다른 의미의 진짜 예약과 구분하기가 조금 아쉬운거 같아요

음 저는 authContext의 함수들이 아니라면 authProps라는 걸로 묶고 있는데
reservationProps는 어떠신가요?

2022-01-29 12:57 UTC, manudeli commented on src/components/domain/ReservationModalContent/HasBallDecisionModal.tsx
> +        )}
하나하나 step을 체크하면서 제목을 구분하지 않고
step별로 모달을 명확히 나누어 놓은 것이 유지보수하기도 좋은 거 같아요👍👍

2022-01-29 12:57 UTC, manudeli commented on src/components/domain/TimeTable/index.tsx
> +    (reservationId: number) => {
후에는 reservationId의 number을 APIReservation의 id를 뽑으면 좋을 거 같아요
```suggestion
    (reservationId: APIReservation["id"]) => {
```
interface의 property type을 구하는 방법이 궁금해서 찾아보니 위와 같이 사용하면 할 수 있다고 하네요~!

![image](https://user-images.githubusercontent.com/61593290/151661784-a4ac456f-3221-4d0b-a248-c66b8291cca0.png)

2022-01-29 13:03 UTC, manudeli commented on src/contexts/ReservationProvider/context.ts
>  }
저는 오늘 context api 타이핑 조질 예정

2022-01-29 19:26 UTC, manudeli commented on src/contexts/ReservationProvider/context.ts
>  }
authProvider 조지고 돌아왔으... 후

2022-01-31 23:52 UTC, manudeli commented
@grighth12 제가 git pull --rebase origin develop 후에 force push해서 한나가 push하실 때 문제가 있었을 거 같아요!!😭
한나 편하라고 conflict 없도록 미리 rebase해놓는다는 게 작업중에 헤매게 했을거 같아서 코멘트 남겨요!! 죄송해요!!

2022-02-04 07:39 UTC, grighth12 commented on src/contexts/ReservationProvider/reducer.ts
> +      console.log(selectedReservationId);
없애겠습니당~~!

2022-02-04 07:43 UTC, grighth12 commented on src/components/domain/TimeTable/index.tsx
>    } = useReservationContext();
~Data, ~Info와 같은 너무 넓은 의미로 사용되는 명사를 붙이는게 좋지 않다고 알고 있어요!  또 props 라고 하면 context의 value인 녀석이니 의미상 조금 맞지 않는게 아닌가 하는 생각이 들기도해요😅

별개로 변수명에 대한 고민은 필요하겠지만.. 어떤게 좋을지 모르겟네요 객체를 좀 더 나누어 구성하면 좋을 것 같긴하네요..!

2022-02-04 07:43 UTC, grighth12 commented on src/components/domain/TimeTable/index.tsx
>    } = useReservationContext();
근데 지금 당장 context 구조를 건드리면 너무 피곤해질 것 같아서,,, 요부분은 일단 패스해보겠습니다...

2022-02-04 07:44 UTC, grighth12 commented on src/components/domain/TimeTable/index.tsx
> +    (reservationId: number) => {
이 부분 타이핑할 때 신경써서 고려해볼게요!! 일단 타이핑은 뒤로 미뤄두겠습니다

2022-02-05 07:50 UTC, grighth12 commented
![스크린샷 2022-02-05 오후 4 49 27](https://user-images.githubusercontent.com/68159627/152633490-1987ce09-912b-49dc-b95f-ae36b0c01fd6.png)
![스크린샷 2022-02-05 오후 4 50 20](https://user-images.githubusercontent.com/68159627/152633511-b6970643-505a-4d51-a647-da63ac748d27.png)

요렇게 완성하였습니다

2022-02-05 08:01 UTC, manudeli commented
![image](https://user-images.githubusercontent.com/61593290/152633744-533902aa-3fa0-45dc-8f08-42563af1cd93.png)
맨아래 하얀색 버튼으로 예약취소만 있으면 완벽할 거 같네요 (네 아니오 외에 예약이 확정되지 않은 상황에서 취소할 방법이 없어 보여서요)
일단 머지하겠습니다! @grighth12 한나는 어떠신가요?

2022-02-05 08:14 UTC, manudeli approved these changes
아직 크리티컬하지는 않지만 제 생각에 타이핑이 선제적으로 되어야 될 거 처럼 보이긴해요
타이핑이 안되어 있어서 코드의 예측이 어렵더라구요

타이핑 우선순위를 올려주시면 좋겠어요 우선 머지할게요

2022-02-05 08:14 UTC, manudeli commented on src/components/domain/ReservationModalContent/HasBallDecisionModal.tsx
> +                        undefined,
`p3`
undefined를 넣는 패턴이 좋아보이지는 않네요~! 
```typescript
const funcComplex = ({a, b, c}) => {} 
```

이런 식으로 쓰신다면 해결 될 수 있을 것 같아요
3개 이상의 인자를 받는 경우엔 고려해볼 수 잇는 패턴이라고 해주시더라구요

2022-02-05 08:14 UTC, manudeli commented on src/contexts/ReservationProvider/index.tsx
> +        type: actionTypes.SET_TIME_INDEX,
`p3`
dispatch에 넣는 action객체가 타이핑이 잘 되어있다면 actionTypes.을 뺄 수 있을 거 같아요
authProvider useReducer쪽에서 dispatch를 써보면 느끼실 거에요 human에러를 타입으로 없애 놨습니다.

다른 이유로는 성능적으로도 다르다고 생각해요 actionTypes를 import할 필요가 없게 되어요
작은 차이겠지만 타입스크립트로 없앨 수 있다면 더 간결한 코드를 쓸 수 있을 거 같아요

2022-02-05 08:14 UTC, manudeli commented on src/components/domain/ReservationModalContent/HasBallDecisionModal.tsx
> +                        undefined,
또 많은 인자를 순서를 고려하지 않고 쓸 수 있기 때문에 좋아요
react component의 props가 좋은 예시인거 같아요

2022-02-05 08:15 UTC, merged

2022-02-05 09:07 UTC, grighth12 commented on src/components/domain/ReservationModalContent/HasBallDecisionModal.tsx
> +                        undefined,
아 맞아요 맞아요 생각하고 있는 부분입니당
추후에 언눙 고쳐보도록 할게요~!

2022-02-06 03:27 UTC, limkhl reviewed
리뷰가 너무 늦어서 죄송해요 😓 한나가 세심하게 고민한 흔적들이 느껴져서 많이 배웠습니다! 🙏

2022-02-06 03:27 UTC, limkhl commented on src/components/domain/ReservationModalContent/HasBallDecisionModal.tsx
> +                        undefined,
이 부분 저도 두번째 인자가 어떤 prop인지 직관적으로 이해되지 않아서 수정하면 좋을 것 같다고 생각했는데 마누 의견 좋네요!