userApi 타이핑 및 프로필 수정 페이지 리팩토링
slamapp/client pull request #92
Opened 2022-02-07 16:20 UTC by manudeli

## 💁 설명 
API 타이핑과 user프로필 수정 페이지 리팩토링 했습니다.
@limkhl 노체는 변경사항 잘 확인해주시고 리뷰로 이해가 되지 않는 부분은 물어봐주세요

- 기존 의도대로 동작하지 않던 에러들을 해결했습니다.
- 불필요한 props를 받아서 생기던 복잡성을 줄이고 상위 컴포넌트 의존성을 끊었습니다.
- 불필요한 reload를 제거했습니다.

## 🔗 연결된 이슈 
closes #91 

## 📸 스크린 샷 
![image](https://user-images.githubusercontent.com/61593290/152828157-14ef91c1-eeb6-4373-ad78-ac7884ba4725.png)

2022-02-07 16:40 UTC, manudeli reviewed
이해를 돕는 코멘트를 남겨요

2022-02-07 16:40 UTC, manudeli commented on src/contexts/AuthProvider/index.tsx
>          });
api의 반환 data 타입과 dispatch할 action객체(type과 payload를 담은 객체)의 타입은 명확히 구분해야합니다.
우리는 타입스크립트를 통해 명확히 이 역할을 분리하고 안전하게 api호출에 따른 전역상태를 관리할 수 있어요

2022-02-07 16:40 UTC, manudeli commented on src/contexts/AuthProvider/index.tsx
> +        // router.reload();
불필요하지만 담당자가 변경점의 위치를 체크할 수 있게 주석으로 달아놨어요

담당자는 테스트하셔서 해결되었는지 체크하시고 왜 해결 되었는지 생각해보시면 좋을 것 같아요
생각해봐도 모르겠다면 저한테 꼭 물어봐주세요

2022-02-07 16:40 UTC, manudeli commented on src/hooks/useForm.ts
> -      }
모달은 form을 위한 것이 아니므로 제거했어요

의존성을 끊어줄 필요가 있어보여서 제거했습니다.

2022-02-07 16:40 UTC, manudeli commented on src/pages/user/edit/index.tsx
> -        handleChangeProficiency={handleChangeProficiency}
이런 컴포넌트 진짜 안되요... 이해하기 너무 어려워요 다음엔 좀 더 문제를 잘 분리해서 생각해봅시다.

2022-02-08 01:13 UTC, manudeli commented on src/hooks/useForm.ts
> -      }
이는 newCourt추가 쪽에 영향이 갈거에요
인지하시고 이슈로 체킹 부탁드립니다

2022-02-08 05:49 UTC, limkhl requested changes
`p1` 프로필 수정 페이지에서 수정된 동작 확인해보려고 했는데 현재 `user/edit` 페이지에 진입할 때 런타임 에러가 나서 확인을 못해봤어요. 제가 지금 디버깅 작업하기 어려울 것 같은데 급하시다고 하시니 이 에러 해결한 뒤에 merge 하시면 될 것 같습니다.
![image](https://user-images.githubusercontent.com/84858773/152925738-c4e77cd0-bb08-4ada-b720-d2045babb03f.png)

2022-02-08 05:49 UTC, limkhl commented on src/components/domain/ProfileForm/index.tsx
> +          console.log(editedProfileImage);
`p2` console.log가 남아 있네요.

2022-02-08 05:49 UTC, limkhl commented on src/hooks/useForm.ts
> -      }
네, 알겠습니다.

2022-02-08 05:49 UTC, limkhl commented on src/contexts/AuthProvider/index.tsx
> +        // router.reload();
에러 때문에 `user/edit` 페이지에 접근이 안돼서 실제 동작이 어떻게 되는지는 확인 못했어요. 에러 해결하신 후에 주석 지우고 merge 해주시면 될 것 같습니다.

2022-02-08 06:41 UTC, manudeli commented on src/contexts/AuthProvider/index.tsx
> +        // router.reload();
노체가 주신 에러메시지를 보니 !로 value를 null이 아닌 것처럼 되엇 잘못된 !으로 인한 에러에요
!사용을 지양해주세요 에러 해결해놨습니다.

2022-02-08 06:41 UTC, manudeli commented on src/contexts/AuthProvider/index.tsx
> +        // router.reload();
들어가셔서 동작방식 확인하시고 reload 주석 지우고 잘 동작하면 approved 후 머지해주세요
담당자이신 분이 이게 없어도 되는 이유를 모르시면 안됩니다.

2022-02-08 06:42 UTC, manudeli commented on src/components/domain/ProfileForm/index.tsx
> +          console.log(editedProfileImage);
제거했습니다

2022-02-08 06:45 UTC, manudeli commented
@limkhl 에러 해결해놨습니다. 노체가 이전에 만드셨던 컴포넌트에 !를 사용하셔서 type에러로 잡히지 않아서 타입스크립트에서 잡아줄 수 있는 부분이 안잡히게 된거에요 !사용은 지양해주세요 혹시 이 부분이 이해가 안가시면 다시 질문해주세요

2022-02-08 07:16 UTC, limkhl approved these changes
동작 확인했습니다. 해결된 이유는 아직 파악을 못했는데 제가 내일까지는 개인 일정이 있어서 코드를 면밀히 살펴보기 어려울 것 같아요. 내일 살펴보고 혹시 이해 안되는 점이 있다면 여쭤보겠습니다. 마누가 작업하는 부분에 영향이 간다고 하니 우선 merge 할게요.

2022-02-08 07:17 UTC, merged